#==============================================================================================
# MODULO 3: ASIGNACION POR MECANISMO ISOES
#==============================================================================================
# Implementa los pasos 2 y 3 del lineamiento (numeral 5.4.1.4):
#   - Ordenamiento intra-IES por ISOES desc, luego menor cohorte, mayor capacidad, semilla
#   - Asignacion iterativa de cupos contra la bolsa IES-Nivel
#   - Reasignacion del excedente IES en bolsa comun por Nivel (Paso 3)
#
# Reproducibilidad: set.seed(20260427) - fecha de generacion del insumo de oferta
#----------------------------------------------------------------------------------------------

#===============================================================================
# FILTRO DE OFERTA HABILITADA
# (Programa habilitado + ejecutoria habilitada + IES con convenio JE4)
#===============================================================================
OFERTA_GENERAL <- unique(LISTADO_OFERTA_PROPUESTA[
  LISTADO_OFERTA_PROPUESTA$PROGRAMA_HABILITADO == "Habilitado" &
    LISTADO_OFERTA_PROPUESTA$HABILITADO_EJECUTORIA == "HABILITADO" &
    !is.na(LISTADO_OFERTA_PROPUESTA$CONVENIO),
])

# Valor de la cohorte para Atenea
OFERTA_GENERAL$TOTAL_VALOR_COHORTE_ATENEA <- OFERTA_GENERAL$TOTAL_VALOR_ATENEA

#===============================================================================
# Paso 2 - i): Ordenamiento de programas dentro de la IES
#===============================================================================
# Criterios (Nota del lineamiento, numeral 5.4.1.4 Paso 2):
#   1. ISOES descendente
#   2. Menor TOTAL_VALOR_COHORTE_ATENEA (menor costo)
#   3. Mayor CUPOS_SEGUN_CAPACIDAD
#   4. Semilla aleatoria auditable

set.seed(20260427)
OFERTA_GENERAL$SEMILLA <- OFERTA_GENERAL$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR[
  sample(length(OFERTA_GENERAL$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR))
]

OFERTAS_CONVENIO_JE4 <- OFERTA_GENERAL[, c(
  "ID", "COD_IES", "NOMBRE_IES", "CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR",
  "NOMBRE_PROGRAMA_SNIES", "JORNADA_DEL_PROGRAMA", "NIVEL_DE_FORMACIÓN",
  "NIVEL_PROGRAMA_SNIES_AJUSTE", "CINE_F_2013_AC_CAMPO_DETALLADO",
  "ISOES_PROGRAMA", "TIR_PROGRAMA", "TOTAL_VALOR_COHORTE_ATENEA",
  "CUPOS_SEGÚN_CAPACIDAD", "SEMILLA", "CONVENIO", "PROGRAMA_HABILITADO",
  "FECHA_EJECUTORIA", "VIGENCIA_AÑOS", "FECHA_EJECUTORIA_FIN",
  "HABILITADO_EJECUTORIA"
)]

ORDENAMIENTO_PROG <- OFERTAS_CONVENIO_JE4 %>%
  arrange(desc(ISOES_PROGRAMA),
          TOTAL_VALOR_COHORTE_ATENEA,
          desc(CUPOS_SEGÚN_CAPACIDAD),
          SEMILLA,
          na.last = TRUE)

ORDENAMIENTO_PROG$ORDENAMIENTO_PROG <- as.double(row.names(ORDENAMIENTO_PROG))

# Pegue demanda historica para uso posterior en el componente de demanda social
ORDENAMIENTO_PROG <- merge(
  x = ORDENAMIENTO_PROG,
  y = DemandaHistorica,
  by.x = c("CINE_F_2013_AC_CAMPO_DETALLADO", "NIVEL_PROGRAMA_SNIES_AJUSTE"),
  by.y = c("DH_CINE_DETALLADO", "DH_NIVEL_PROGRAMA_SNIES_AJUSTE"),
  all.x = TRUE
)

OFERTA_GENERAL <- merge(
  x = ORDENAMIENTO_PROG[, c("ORDENAMIENTO_PROG", "ID", "DH_INSCRITOS", "DH_CUPOS",
                           "DH_INDICADOR_DEMANDA_SOCIAL",
                           "DH_PERCENTIL_50_(POR_ENCIMA_/_POR_DEBAJO)")],
  y = OFERTA_GENERAL,
  by = "ID",
  all = FALSE
)

# Identificador IES x Nivel para el recorrido
IES <- PRESUPUESTO_IES_NIVEL %>%
  arrange(COD_IES, NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  mutate(ID_IES_NIVEL = row_number())

# Construccion de las bolsas
IES$VALOR_SOBRANTE_IES_NIVEL          <- IES$VALOR_DISTRIBUCION_IES_NIVEL
ORDENAMIENTO_PROG$CUPO_ASIGNADO_IES   <- 0
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_IES <- 0

#===============================================================================
# Paso 2 - ii a iv): Asignacion iterativa intra-IES
#===============================================================================
# Por cada (IES, Nivel) se recorren sus programas en el orden definido y se
# asignan cupos mientras alcance la bolsa de la IES.

for (ID_IES_NIVEL in unique(IES$ID_IES_NIVEL)) {
  print(paste("ORDEN_IES_", ID_IES_NIVEL))

  EVALUAR_IES <- IES[IES$ID_IES_NIVEL == ID_IES_NIVEL, ]
  print(paste(EVALUAR_IES$SNIES_PADRE,
              EVALUAR_IES$NIVEL_PROGRAMA_SNIES_AJUSTE,
              EVALUAR_IES$VALOR_SOBRANTE_IES_NIVEL,
              sep = " "))

  SEMILLA_PROGRAMAS <- ORDENAMIENTO_PROG[
    ORDENAMIENTO_PROG$COD_IES == EVALUAR_IES$COD_IES &
      ORDENAMIENTO_PROG$NIVEL_PROGRAMA_SNIES_AJUSTE == EVALUAR_IES$NIVEL_PROGRAMA_SNIES_AJUSTE,
  ]
  SEMILLA_PROGRAMAS <- SEMILLA_PROGRAMAS[order(SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG), ]

  for (ID_PROGRAMA in SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG) {
    print(paste(" ORDEN_PROG_", ID_PROGRAMA))
    EVALUAR_PROG <- SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, ]

    VALOR_IES <- IES[IES$ID_IES_NIVEL == ID_IES_NIVEL, "VALOR_SOBRANTE_IES_NIVEL"]

    if (nrow(EVALUAR_PROG) == 0) {
      CUPO_OFERTADO  <- 0
      CUPO_CALCULADO <- 0
      TOTAL_COHORTE  <- 0
    } else {
      CUPO_OFERTADO  <- EVALUAR_PROG$CUPOS_SEGÚN_CAPACIDAD
      CUPO_CALCULADO <- VALOR_IES / EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA
      TOTAL_COHORTE  <- EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA
    }

    # Regla 1: el presupuesto alcanza para todos los cupos ofertados
    if (CUPO_CALCULADO >= CUPO_OFERTADO) {
      print("es cupo ofertado")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_IES"] <- CUPO_OFERTADO
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_IES"] <- CUPO_OFERTADO

      COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_IES"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_IES"] <- COSTO_CUPOS

      VALOR_IES <- VALOR_IES - COSTO_CUPOS
      IES[IES$ID_IES_NIVEL == ID_IES_NIVEL, "VALOR_SOBRANTE_IES_NIVEL"] <- VALOR_IES

    } else if (CUPO_CALCULADO < CUPO_OFERTADO & as.integer(CUPO_CALCULADO) > 0) {
      # Regla 2: alcanza para al menos 1 cupo, se trunca al entero
      print("es cupo calculado")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_IES"] <- as.integer(CUPO_CALCULADO)
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_IES"] <- as.integer(CUPO_CALCULADO)

      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_IES"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_IES"] <- COSTO_CUPOS

      VALOR_IES <- VALOR_IES - COSTO_CUPOS
      IES[IES$ID_IES_NIVEL == ID_IES_NIVEL, "VALOR_SOBRANTE_IES_NIVEL"] <- VALOR_IES

    } else {
      print(paste("----------- NO ALCANZA PRESUPUESTO ",
                  EVALUAR_PROG$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR,
                  " CUPO CALCULADO =", CUPO_CALCULADO))
    }
  } # fin recorrido programas
} # fin recorrido IES x Nivel

#===============================================================================
# Paso 3: Asignacion del excedente en bolsa comun por Nivel
#===============================================================================
# Los sobrantes por IES se agrupan por Nivel y se reasignan a programas que
# aun tienen cupos pendientes, respetando el orden ISOES.

EXCEDENTE_NIVEL <- IES %>%
  group_by(NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  summarise_at(vars(VALOR_SOBRANTE_IES_NIVEL),
               list(VALOR_SOBRANTE_NIVEL = sum))
EXCEDENTE_NIVEL <- EXCEDENTE_NIVEL %>%
  arrange(NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  mutate(ID_NIVEL = row_number())
EXCEDENTE_NIVEL$VALOR_SOBRANTE_NIVEL_ORI <- EXCEDENTE_NIVEL$VALOR_SOBRANTE_NIVEL

# Cupos pendientes por programa luego del Paso 2
ORDENAMIENTO_PROG$CUPO_PENDIENTES        <- ORDENAMIENTO_PROG$CUPOS_SEGÚN_CAPACIDAD - ORDENAMIENTO_PROG$CUPO_ASIGNADO_IES
ORDENAMIENTO_PROG$CUPO_ASIGNADO_NIVEL    <- 0
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_NIVEL <- 0

ASIGNACION_NIVEL_PROG <- ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$CUPO_PENDIENTES > 0, ]
ASIGNACION_NIVEL_PROG <- merge(
  x = ASIGNACION_NIVEL_PROG,
  y = IES[, c("COD_IES", "NIVEL_PROGRAMA_SNIES_AJUSTE", "ID_IES_NIVEL")],
  by  = c("COD_IES", "NIVEL_PROGRAMA_SNIES_AJUSTE"),
  all = FALSE
)

for (ID_NIVEL in unique(EXCEDENTE_NIVEL$ID_NIVEL)) {
  print(paste("ORDEN_NIVEL ", ID_NIVEL))

  EVALUAR_NIVEL <- EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, ]

  SEMILLA_PROGRAMAS <- ASIGNACION_NIVEL_PROG[
    ASIGNACION_NIVEL_PROG$NIVEL_PROGRAMA_SNIES_AJUSTE == EVALUAR_NIVEL$NIVEL_PROGRAMA_SNIES_AJUSTE,
  ]
  SEMILLA_PROGRAMAS <- SEMILLA_PROGRAMAS[order(SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG), ]

  for (ID_PROGRAMA in SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG) {
    print(paste(" ORDEN_PROG_", ID_PROGRAMA))
    EVALUAR_PROG <- SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, ]

    VALOR_NIVEL    <- EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"]
    CUPO_OFERTADO  <- EVALUAR_PROG$CUPO_PENDIENTES
    CUPO_CALCULADO <- VALOR_NIVEL / EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA
    TOTAL_COHORTE  <- EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA

    if (CUPO_CALCULADO >= CUPO_OFERTADO) {
      print("es cupo ofertado")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- CUPO_OFERTADO
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- CUPO_OFERTADO
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- CUPO_OFERTADO

      COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS

      VALOR_NIVEL <- VALOR_NIVEL - COSTO_CUPOS
      EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"] <- VALOR_NIVEL

    } else if (CUPO_CALCULADO < CUPO_OFERTADO & as.integer(CUPO_CALCULADO) > 0) {
      print("es cupo calculado")
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- as.integer(CUPO_CALCULADO)
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- as.integer(CUPO_CALCULADO)
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL"] <- as.integer(CUPO_CALCULADO)

      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL"] <- COSTO_CUPOS

      VALOR_NIVEL <- VALOR_NIVEL - COSTO_CUPOS
      EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"] <- VALOR_NIVEL

    } else {
      print(paste("----------- NO ALCANZA PRESUPUESTO ",
                  EVALUAR_PROG$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR,
                  " CUPO CALCULADO =", CUPO_CALCULADO))
    }
  } # fin recorrido programas
} # fin recorrido niveles

#-------------------------------------------------------------------------------
# Consolidacion mecanismo ISOES (Paso 2 + Paso 3)
#-------------------------------------------------------------------------------
ORDENAMIENTO_PROG$CUPOS_ASIGNADOS_MECANISMO_ACTUAL <-
  ORDENAMIENTO_PROG$CUPO_ASIGNADO_IES + ORDENAMIENTO_PROG$CUPO_ASIGNADO_NIVEL
ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADOS_MECANISMO_ACTUAL <-
  ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_IES + ORDENAMIENTO_PROG$COSTO_CUPOS_ASIGNADO_NIVEL

# Actualizacion de cupos pendientes para la fase de demanda social
ORDENAMIENTO_PROG$CUPO_PENDIENTES <-
  ORDENAMIENTO_PROG$CUPOS_SEGÚN_CAPACIDAD - ORDENAMIENTO_PROG$CUPOS_ASIGNADOS_MECANISMO_ACTUAL
