#==============================================================================================
# MODULO 4: COMPONENTE DE ALTA DEMANDA SOCIAL
#==============================================================================================
# Implementa la Actividad 3 del lineamiento (numeral 5.4.1.5):
#   - Universo: programas con <6 cupos asignados via ISOES y por encima del percentil 50
#     en el indicador de demanda social (inscritos / cupos por CINE F detallado)
#   - Bolsa: 10% del PPTO_GENERAL + excedente ISOES, distribuido 95% UNI / 5% TyT
#   - Distribucion por bolsas CINE x Nivel proporcional a inscritos historicos (DH_INSCRITOS)
#   - Recorrido analogo al Modulo 3 (Paso 2 dentro de bolsa CINE + Paso 3 excedente por Nivel)
#----------------------------------------------------------------------------------------------

# Recalculo del presupuesto de demanda social: 10% original + excedente del mecanismo ISOES
EXCEDENTE_MECANISMO_ACTUAL <- sum(EXCEDENTE_NIVEL$VALOR_SOBRANTE_NIVEL)
PPTO_DemandaSocial         <- PPTO_DemandaSocial + EXCEDENTE_MECANISMO_ACTUAL

#===============================================================================
# Filtrado de programas elegibles para demanda social
#===============================================================================
# 1) Programas con menos de 6 cupos asignados via mecanismo ISOES
CONTEO_DEMANDA_SOCIAL <- ORDENAMIENTO_PROG %>%
  group_by(CINE_F_2013_AC_CAMPO_DETALLADO) %>%
  summarise_at(vars(CUPOS_ASIGNADOS_MECANISMO_ACTUAL),
               list(TOTAL_CUPOS_MECANISMO_ACTUAL = sum))
CONTEO_DEMANDA_SOCIAL <- CONTEO_DEMANDA_SOCIAL[
  CONTEO_DEMANDA_SOCIAL$TOTAL_CUPOS_MECANISMO_ACTUAL < 6, ]

# 2) Cruce con programas que tienen cupos pendientes
OFERTA_DEMANDA_SOCIAL <- merge(
  x = CONTEO_DEMANDA_SOCIAL,
  y = ORDENAMIENTO_PROG[ORDENAMIENTO_PROG$CUPO_PENDIENTES > 0, ],
  by  = "CINE_F_2013_AC_CAMPO_DETALLADO",
  all = FALSE
)
OFERTA_DEMANDA_SOCIAL <- OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$CUPO_PENDIENTES > 0, ]

# 3) Registros con indicador de demanda social disponible
OFERTA_DEMANDA_SOCIAL <- OFERTA_DEMANDA_SOCIAL[
  !is.na(OFERTA_DEMANDA_SOCIAL$DH_INDICADOR_DEMANDA_SOCIAL), ]

# 4) Programas por encima del percentil 50 en demanda social (segun nivel)
OFERTA_DEMANDA_SOCIAL <- OFERTA_DEMANDA_SOCIAL[
  OFERTA_DEMANDA_SOCIAL$`DH_PERCENTIL_50_(POR_ENCIMA_/_POR_DEBAJO)` == "POR ENCIMA PERCENTIL 50", ]

#===============================================================================
# Paso 1.1 Demanda Social: Presupuesto CINE x Nivel (% segun inscritos JE2)
#===============================================================================
CINE_NIVEL <- unique(OFERTA_DEMANDA_SOCIAL[, c("CINE_F_2013_AC_CAMPO_DETALLADO",
                                              "NIVEL_PROGRAMA_SNIES_AJUSTE",
                                              "DH_INSCRITOS")])

CINE <- CINE_NIVEL %>%
  group_by(NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  summarise_at(vars(DH_INSCRITOS), list(TOTAL_BENEF_NIVEL = sum))

CINE_NIVEL <- merge(x = CINE_NIVEL, y = CINE,
                    by = "NIVEL_PROGRAMA_SNIES_AJUSTE", all = FALSE)
CINE_NIVEL$DISTRIBUCION_CINE_NIVEL <- CINE_NIVEL$DH_INSCRITOS / CINE_NIVEL$TOTAL_BENEF_NIVEL

# Distribucion 95% Universitario / 5% TyT sobre el presupuesto de demanda social
PPTO_DemandaSocial_TYT <- PPTO_DemandaSocial * 0.05
PPTO_DemandaSocial_UNI <- PPTO_DemandaSocial * 0.95

CINE_NIVEL$PPTO_DemandaSocial <- 0
CINE_NIVEL[CINE_NIVEL$NIVEL_PROGRAMA_SNIES_AJUSTE == "TYT",          "PPTO_DemandaSocial"] <- PPTO_DemandaSocial_TYT
CINE_NIVEL[CINE_NIVEL$NIVEL_PROGRAMA_SNIES_AJUSTE == "UNIVERSITARIO","PPTO_DemandaSocial"] <- PPTO_DemandaSocial_UNI

CINE_NIVEL$VALOR_DISTRIBUCION_CINE_NIVEL <-
  CINE_NIVEL$DISTRIBUCION_CINE_NIVEL * CINE_NIVEL$PPTO_DemandaSocial

# Identificador CINE x Nivel para el recorrido
CINE_NIVEL <- CINE_NIVEL %>%
  arrange(CINE_F_2013_AC_CAMPO_DETALLADO, NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  mutate(ID_CINE_NIVEL = row_number())

CINE_NIVEL$VALOR_SOBRANTE_CINE_NIVEL    <- CINE_NIVEL$VALOR_DISTRIBUCION_CINE_NIVEL
OFERTA_DEMANDA_SOCIAL$CUPO_ASIGNADO_CINE         <- 0
OFERTA_DEMANDA_SOCIAL$COSTO_CUPOS_ASIGNADO_CINE  <- 0

#===============================================================================
# Asignacion por bolsa CINE x Nivel
#===============================================================================
for (ID_CINE_NIVEL in unique(CINE_NIVEL$ID_CINE_NIVEL)) {
  print(paste("ORDEN_CINE_", ID_CINE_NIVEL))

  EVALUAR_CINE <- CINE_NIVEL[CINE_NIVEL$ID_CINE_NIVEL == ID_CINE_NIVEL, ]
  print(paste(EVALUAR_CINE$CINE_F_2013_AC_CAMPO_DETALLADO,
              EVALUAR_CINE$NIVEL_PROGRAMA_SNIES_AJUSTE,
              EVALUAR_CINE$VALOR_SOBRANTE_CINE_NIVEL, sep = "|"))

  SEMILLA_PROGRAMAS <- OFERTA_DEMANDA_SOCIAL[
    OFERTA_DEMANDA_SOCIAL$CINE_F_2013_AC_CAMPO_DETALLADO == EVALUAR_CINE$CINE_F_2013_AC_CAMPO_DETALLADO &
      OFERTA_DEMANDA_SOCIAL$NIVEL_PROGRAMA_SNIES_AJUSTE == EVALUAR_CINE$NIVEL_PROGRAMA_SNIES_AJUSTE,
  ]
  SEMILLA_PROGRAMAS <- SEMILLA_PROGRAMAS[order(SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG), ]

  for (ID_PROGRAMA in SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG) {
    print(paste(" ORDEN_PROG_", ID_PROGRAMA))
    EVALUAR_PROG <- SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, ]

    VALOR_CINE     <- CINE_NIVEL[CINE_NIVEL$ID_CINE_NIVEL == ID_CINE_NIVEL, "VALOR_SOBRANTE_CINE_NIVEL"]
    CUPO_OFERTADO  <- EVALUAR_PROG$CUPOS_SEGÚN_CAPACIDAD
    CUPO_CALCULADO <- VALOR_CINE / EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA
    TOTAL_COHORTE  <- EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA

    if (CUPO_CALCULADO >= CUPO_OFERTADO) {
      print("es cupo ofertado")
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_CINE"] <- CUPO_OFERTADO
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_CINE"] <- CUPO_OFERTADO

      COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_CINE"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_CINE"] <- COSTO_CUPOS

      VALOR_CINE <- VALOR_CINE - COSTO_CUPOS
      CINE_NIVEL[CINE_NIVEL$ID_CINE_NIVEL == ID_CINE_NIVEL, "VALOR_SOBRANTE_CINE_NIVEL"] <- VALOR_CINE

    } else if (CUPO_CALCULADO < CUPO_OFERTADO & as.integer(CUPO_CALCULADO) > 0) {
      print("es cupo calculado")
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_CINE"] <- as.integer(CUPO_CALCULADO)
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_CINE"] <- as.integer(CUPO_CALCULADO)

      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_CINE"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_CINE"] <- COSTO_CUPOS

      VALOR_CINE <- VALOR_CINE - COSTO_CUPOS
      CINE_NIVEL[CINE_NIVEL$ID_CINE_NIVEL == ID_CINE_NIVEL, "VALOR_SOBRANTE_CINE_NIVEL"] <- VALOR_CINE

    } else {
      print(paste("----------- NO ALCANZA PRESUPUESTO ",
                  EVALUAR_PROG$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR,
                  " CUPO CALCULADO =", CUPO_CALCULADO))
    }
  } # fin recorrido programas
} # fin recorrido CINE x Nivel

#===============================================================================
# Paso 3 Demanda Social: Excedente CINE -> Bolsa comun por Nivel
#===============================================================================
EXCEDENTE_NIVEL <- CINE_NIVEL %>%
  group_by(NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  summarise_at(vars(VALOR_SOBRANTE_CINE_NIVEL),
               list(VALOR_SOBRANTE_NIVEL = sum))
EXCEDENTE_NIVEL <- EXCEDENTE_NIVEL %>%
  arrange(NIVEL_PROGRAMA_SNIES_AJUSTE) %>%
  mutate(ID_NIVEL = row_number())
EXCEDENTE_NIVEL$VALOR_SOBRANTE_NIVEL_ORI <- EXCEDENTE_NIVEL$VALOR_SOBRANTE_NIVEL

# Cupos pendientes despues de la asignacion por CINE
OFERTA_DEMANDA_SOCIAL$CUPO_PENDIENTES <- OFERTA_DEMANDA_SOCIAL$CUPOS_SEGÚN_CAPACIDAD -
  (OFERTA_DEMANDA_SOCIAL$CUPOS_ASIGNADOS_MECANISMO_ACTUAL +
     OFERTA_DEMANDA_SOCIAL$CUPO_ASIGNADO_CINE)
OFERTA_DEMANDA_SOCIAL$CUPO_ASIGNADO_NIVEL_DH        <- 0
OFERTA_DEMANDA_SOCIAL$COSTO_CUPOS_ASIGNADO_NIVEL_DH <- 0

ASIGNACION_NIVEL_PROG <- OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$CUPO_PENDIENTES > 0, ]

for (ID_NIVEL in unique(EXCEDENTE_NIVEL$ID_NIVEL)) {
  print(paste("ORDEN_NIVEL ", ID_NIVEL))

  EVALUAR_NIVEL <- EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, ]

  SEMILLA_PROGRAMAS <- ASIGNACION_NIVEL_PROG[
    ASIGNACION_NIVEL_PROG$NIVEL_PROGRAMA_SNIES_AJUSTE == EVALUAR_NIVEL$NIVEL_PROGRAMA_SNIES_AJUSTE,
  ]
  SEMILLA_PROGRAMAS <- SEMILLA_PROGRAMAS[order(SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG), ]

  for (ID_PROGRAMA in SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG) {
    print(paste(" ORDEN_PROG_", ID_PROGRAMA))
    EVALUAR_PROG <- SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, ]

    VALOR_NIVEL    <- EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"]
    CUPO_OFERTADO  <- EVALUAR_PROG$CUPO_PENDIENTES
    CUPO_CALCULADO <- VALOR_NIVEL / EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA
    TOTAL_COHORTE  <- EVALUAR_PROG$TOTAL_VALOR_COHORTE_ATENEA

    if (CUPO_CALCULADO >= CUPO_OFERTADO) {
      print("es cupo ofertado")
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- CUPO_OFERTADO
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- CUPO_OFERTADO
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- CUPO_OFERTADO

      COSTO_CUPOS <- CUPO_OFERTADO * TOTAL_COHORTE
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS

      VALOR_NIVEL <- VALOR_NIVEL - COSTO_CUPOS
      EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"] <- VALOR_NIVEL

    } else if (CUPO_CALCULADO < CUPO_OFERTADO & as.integer(CUPO_CALCULADO) > 0) {
      print("es cupo calculado")
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- as.integer(CUPO_CALCULADO)
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- as.integer(CUPO_CALCULADO)
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "CUPO_ASIGNADO_NIVEL_DH"] <- as.integer(CUPO_CALCULADO)

      COSTO_CUPOS <- as.integer(CUPO_CALCULADO) * TOTAL_COHORTE
      OFERTA_DEMANDA_SOCIAL[OFERTA_DEMANDA_SOCIAL$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS
      SEMILLA_PROGRAMAS[SEMILLA_PROGRAMAS$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS
      ASIGNACION_NIVEL_PROG[ASIGNACION_NIVEL_PROG$ORDENAMIENTO_PROG == ID_PROGRAMA, "COSTO_CUPOS_ASIGNADO_NIVEL_DH"] <- COSTO_CUPOS

      VALOR_NIVEL <- VALOR_NIVEL - COSTO_CUPOS
      EXCEDENTE_NIVEL[EXCEDENTE_NIVEL$ID_NIVEL == ID_NIVEL, "VALOR_SOBRANTE_NIVEL"] <- VALOR_NIVEL

    } else {
      print(paste("----------- NO ALCANZA PRESUPUESTO ",
                  EVALUAR_PROG$CÓDIGO_SNIES_DEL_PROGRAMA_A_OFERTAR,
                  " CUPO CALCULADO =", CUPO_CALCULADO))
    }
  } # fin recorrido programas
} # fin recorrido niveles

#-------------------------------------------------------------------------------
# Consolidacion del componente de demanda social
#-------------------------------------------------------------------------------
OFERTA_DEMANDA_SOCIAL$CUPOS_ASIGNADOS_DEMANDA_SOCIAL <-
  OFERTA_DEMANDA_SOCIAL$CUPO_ASIGNADO_CINE + OFERTA_DEMANDA_SOCIAL$CUPO_ASIGNADO_NIVEL_DH
OFERTA_DEMANDA_SOCIAL$COSTO_CUPOS_DEMANDA_SOCIAL <-
  OFERTA_DEMANDA_SOCIAL$COSTO_CUPOS_ASIGNADO_CINE + OFERTA_DEMANDA_SOCIAL$COSTO_CUPOS_ASIGNADO_NIVEL_DH

OFERTA_DEMANDA_SOCIAL$EVALUADO_DEMANDA_SOCIAL <- "S"
